const needsKey = {
	belly: "to breathe into my belly",
	talk: "to talk to someone",
	breathing: "to focus on my breathing",
	ground: "to ground in the present",
	sleep: "to rest or sleep",
	cry: "to cry",
	hug: "a hug or a snuggle",
	snack: "a snack",
	no: 'to say "no"',
	discharge: "to discharge energy",
	"discharge-purple": "to discharge energy",
	"discharge-red": "to discharge energy",
	learn: "to learn more",
	make: "to make something",
	savor: "savor it",
	smile: "smile",
	celebrate: "celebrate!",
	smile: "smile",
	leave: "to leave or be further away",
	slow: "to slow down",
	exit: "to find an exit",
	stomach: "to throw up/get something out of my stomach",
	discomfort: "to talk about/share something causing discomfort",
	investigate: "to investigate something for myself",
	judgement: "to suspend judgement",
	bite: "to take a very small bite",
	information: "more information, clarity, or understanding",
	heard: "to be heard/noticed",
	boundary: "to set a new boundary",
	glucose: "a snack/more glucose",
	rest: "rest",
	break: "a break",
	attention: "attention",
	touch: "consensual physical touch",
	remember: "to remember",
	friendship: "friendship",
	sing: "to sing",
	play: "to play",
	act: "to act",
	dance: "to dance",
	explore: "to explore",
	write: "to write",
	wiggle: "to wiggle!",
	remember: "remember this for later"
};

export default needsKey;
