const needsKey = {
	breath: "to focus on my breath or change my breathing",
	breathing: "to focus on my breathing",
	discharge: "to discharge energy",
	"discharge-purple": "to discharge energy",
	calm: "to find a calm place in my mind",
	slow: "to slow down",
	speed: "to speed up",
	ground: "to ground in the present",
	information: "more information, clarity or understanding",
	heard: "to be heard/noticed",
	no: "to say no",
	boundary: "to set a new boundary",
	"discharge-red": "to discharge energy",
	snack: "a snack",
	glucose: "a snack/more glucose",
	sleep: "to rest or sleep",
	break: "to take a break",
	attention: "to ask for attention",
	touch: "consensual physical touch",
	hug: "a hug or a snuggle",
	cry: "to cry",
	remember: "to remember",
	nice: "to do something nice for myself",
	suspend: "to suspend judgement",
	talk: "to talk about/share something causing discomfort",
	someone: "to talk to someone",
	release: "to release something",
	belly: "to breathe into or engage my belly",
	savor: "savor it",
	celebrate: "celebrate!",
	rest: "rest",
	later: "remember this moment for later",
	share: "to share my wisdom",
	play: "to play",
	dance: "to dance",
	sing: "to sing",
	explore: "to explore",
	write: "to write",
	action: "to take action",
	learn: "to learn more",
	make: "to make something"
};

export default needsKey;
